### ISSUE TITLE
The renaming sql_query/2 to query/2

### ISSUE THREAD

**Issue by ghost** [extend/bank_mysql#10]
Hi,

I think, renaming sql_query/2 to query/2 wasn't such a good idea, as the atom 'query' is a reserved word in Erlang.

http://erlang.org/doc/reference_manual/introduction.html#id69675

'matthias'.

**Comment by essen** [comment]
Not since R16B. I personally removed it. Guess I missed that documentation page.

**Comment by ghost** [comment]
Okay, so then the Erlang documentation is wrong.

**Comment by ghost** [comment]
Now you know about it :-)

**Comment by essen** [comment]
Sent to erlang-patches. Thanks!
