### ISSUE TITLE
no match error in parse_handshake_init/1 

### ISSUE THREAD

**Issue by ghost** [extend/bank_mysql#3]
Hi!

This no match happens if the MySQL server doesn't send the auth-plugin in the initial_handshake packet.

You can find a fix here: https://github.com/pannonia-technologies/bank_mysql/commit/703d39d792964b4a3b89af087d8f6fb3205ac263

Sorry, the fix above is broken... damn, just too late at night again ;-). So you also need the fix of the fix commit: https://github.com/pannonia-technologies/bank_mysql/commit/8b06ed55d5636ce9ddb233140d1d09458176e4f5

'matthias'.

**Comment by essen** [comment]
Can you send a pull request for it, adding a short comment explaining, with a single commit? Thanks!

**Comment by ghost** [comment]
Will do this later tonight!

**Comment by ghost** [comment]
I think we can close this now.
