### ISSUE TITLE
get rid of name clash compiler warnings

### ISSUE THREAD

**Issue by ghost** [extend/bank_mysql#4]
Hi!

Please consider getting rid of the compiler warnings. So the project compiles, even if you are pedantic and paranoid like me, when compiling everything with option warnings_as_errors set.

Here's a suggestion:

https://github.com/pannonia-technologies/bank_mysql/commit/4c8c11a3b18e1ee45a1521fb1e99474f67d9f335

'matthias'.

**Comment by essen** [comment]
It hasn't been tested with R16B yet I guess. We are planning to make bank require R16B very soon so these functions will likely simply be removed.

**Comment by ghost** [comment]
Ah, okay. This makes sense... Never noticed these new useful BIFs in R16B.

**Comment by ghost** [comment]
I think we can close this now.
